name: Monorepo CI/CD to GCP Cloud Run

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: your-gcp-project-id
  GCP_REGION: us-central1

jobs:
  # --- Deploy Python FastAPI Backend Service ---
  deploy-python-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for Python Backend Changes
        id: check_python_changes
        run: |
          echo "--- Debugging Python Changes ---"
          echo "Current directory contents:"
          ls -laR ./option-recommender-python/

          if git diff --quiet "${{ github.event.before }}" "${{ github.sha }}" -- option-recommender-python/; then
            echo "No changes detected in option-recommender-python/"
            echo "python_changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in option-recommender-python/"
            echo "python_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Debug Output
        run: echo "Python Changed: ${{ steps.check_python_changes.outputs.python_changed }}"

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy Python Backend to Cloud Run
        if: steps.check_python_changes.outputs.python_changed == 'true'
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: recommender-python-api
          region: ${{ env.GCP_REGION }}
          source: ./option-recommender-python
          flags: |
            --allow-unauthenticated
            --port 8000

  # --- Deploy Java Spring Boot Backend Service ---
  deploy-java-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for Java Backend Changes
        id: check_java_changes
        run: |
          echo "--- Debugging Java Changes ---"
          echo "Current directory contents:"
          ls -laR ./option-recommender-java/

          if git diff --quiet "${{ github.event.before }}" "${{ github.sha }}" -- option-recommender-java/; then
            echo "No changes detected in option-recommender-java/"
            echo "java_changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in option-recommender-java/"
            echo "java_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Debug Output
        run: echo "Java Changed: ${{ steps.check_java_changes.outputs.java_changed }}"

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up JDK 17
        if: steps.check_java_changes.outputs.java_changed == 'true'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Java Backend with Maven
        if: steps.check_java_changes.outputs.java_changed == 'true'
        run: mvn clean package -DskipTests
        working-directory: ./option-recommender-java

      - name: Deploy Java Backend to Cloud Run
        if: steps.check_java_changes.outputs.java_changed == 'true'
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: recommender-java-backend
          region: ${{ env.GCP_REGION }}
          source: ./option-recommender-java
          flags: |
            --allow-unauthenticated
            --port 8080

  # --- Deploy React/Vite Frontend Service ---
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for Frontend Changes
        id: check_frontend_changes
        run: |
          echo "--- Debugging Frontend Changes ---"
          echo "Current directory contents:"
          ls -laR ./option-recommender-frontend/options-ui/

          if git diff --quiet "${{ github.event.before }}" "${{ github.sha }}" -- option-recommender-frontend/options-ui/; then
            echo "No changes detected in option-recommender-frontend/options-ui/"
            echo "frontend_changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in option-recommender-frontend/options-ui/"
            echo "frontend_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Debug Output
        run: echo "Frontend Changed: ${{ steps.check_frontend_changes.outputs.frontend_changed }}"

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Node.js
        if: steps.check_frontend_changes.outputs.frontend_changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Create .env.production
        if: steps.check_frontend_changes.outputs.frontend_changed == 'true'
        run: |
          echo "REACT_APP_JAVA_API_URL=${{ secrets.REACT_APP_JAVA_API_URL }}" > ./option-recommender-frontend/options-ui/.env.production
          echo "REACT_APP_PYTHON_API_URL=${{ secrets.REACT_APP_PYTHON_API_URL }}" >> ./option-recommender-frontend/options-ui/.env.production
          echo "Contents of .env.production:"
          cat ./option-recommender-frontend/options-ui/.env.production

      - name: Install Frontend Dependencies
        if: steps.check_frontend_changes.outputs.frontend_changed == 'true'
        run: npm ci
        working-directory: ./option-recommender-frontend/options-ui

      - name: Build React App
        if: steps.check_frontend_changes.outputs.frontend_changed == 'true'
        run: npm run build
        working-directory: ./option-recommender-frontend/options-ui

      - name: Deploy Frontend to Cloud Run
        if: steps.check_frontend_changes.outputs.frontend_changed == 'true'
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: recommender-frontend-service
          region: ${{ env.GCP_REGION }}
          source: ./option-recommender-frontend/options-ui
          flags: |
            --allow-unauthenticated
            --port 80
