name: Monorepo CI/CD to GCP Cloud Run

on:
  push:
    branches:
      - main # This workflow triggers on pushes to the 'main' branch

env:
  GCP_PROJECT_ID: option-recommender 
  GCP_REGION: us-central1             

jobs:
  # --- Deploy Python FastAPI Backend Service ---
  deploy-python-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for Python Backend Changes
        id: check_python_changes
        run: |
          git diff --quiet ${{ github.event.before }} ${{ github.sha }} -- option-recommender-python/ || echo "python_changed=true" >> "$GITHUB_OUTPUT"
        if: steps.check_python_changes.outputs.python_changed == 'true'

      - name: Authenticate to GCP
        if: steps.check_python_changes.outputs.python_changed == 'true'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy Python Backend to Cloud Run
        if: steps.check_python_changes.outputs.python_changed == 'true'
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: recommender-python-api
          region: ${{ env.GCP_REGION }}
          source: ./option-recommender-python
          # Removed --min-instances 1 to allow scaling to zero for free tier
          flags: |
            --allow-unauthenticated
            --port 8000
          # env: # Optional: Pass environment variables to the Cloud Run service
          #   DB_HOST: ${{ secrets.PYTHON_DB_HOST }}

  # --- Deploy Java Spring Boot Backend Service ---
  deploy-java-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for Java Backend Changes
        id: check_java_changes
        run: |
          git diff --quiet ${{ github.event.before }} ${{ github.sha }} -- option-recommender-java/ || echo "java_changed=true" >> "$GITHUB_OUTPUT"
        if: steps.check_java_changes.outputs.java_changed == 'true'

      - name: Authenticate to GCP
        if: steps.check_java_changes.outputs.java_changed == 'true'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up JDK 21
        if: steps.check_java_changes.outputs.java_changed == 'true'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Java Backend with Maven
        if: steps.check_java_changes.outputs.java_changed == 'true'
        run: mvn clean package -DskipTests
        working-directory: ./option-recommender-java

      - name: Deploy Java Backend to Cloud Run
        if: steps.check_java_changes.outputs.java_changed == 'true'
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: recommender-java-backend
          region: ${{ env.GCP_REGION }}
          source: ./option-recommender-java
          # Removed --min-instances 1 to allow scaling to zero for free tier
          flags: |
            --allow-unauthenticated
            --port 8080
          # env: # Optional: Pass environment variables to the Cloud Run service
          #   DB_HOST: ${{ secrets.JAVA_DB_HOST }}

  # --- Deploy React/Vite Frontend Service ---
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for Frontend Changes
        id: check_frontend_changes
        run: |
          git diff --quiet ${{ github.event.before }} ${{ github.sha }} -- option-recommender-frontend/options-ui/ || echo "frontend_changed=true" >> "$GITHUB_OUTPUT"
        if: steps.check_frontend_changes.outputs.frontend_changed == 'true'

      - name: Authenticate to GCP
        if: steps.check_frontend_changes.outputs.frontend_changed == 'true'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Node.js
        if: steps.check_frontend_changes.outputs.frontend_changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '18'

          # --- Create .env.production file for React build ---
      - name: Create .env.production
        if: steps.check_frontend_changes.outputs.frontend_changed == 'true'
        run: |
          echo "REACT_APP_JAVA_API_URL=${{ secrets.REACT_APP_JAVA_API_URL }}" > ./option-recommender-frontend/options-ui/.env.production
          echo "REACT_APP_PYTHON_API_URL=${{ secrets.REACT_APP_PYTHON_API_URL }}" >> ./option-recommender-frontend/options-ui/.env.production
          cat ./option-recommender-frontend/options-ui/.env.production # For debugging: print content
          # --- END NEW STEP ---

      - name: Install Frontend Dependencies
        if: steps.check_frontend_changes.outputs.frontend_changed == 'true'
        run: npm ci
        working-directory: ./option-recommender-frontend/options-ui

      - name: Build React App
        if: steps.check_frontend_changes.outputs.frontend_changed == 'true'
        run: npm run build
        working-directory: ./option-recommender-frontend/options-ui

      - name: Deploy Frontend to Cloud Run
        if: steps.check_frontend_changes.outputs.frontend_changed == 'true'
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: recommender-frontend-service
          region: ${{ env.GCP_REGION }}
          source: ./option-recommender-frontend/options-ui
          # Removed --min-instances 1 to allow scaling to zero for free tier
          flags: |
            --allow-unauthenticated
            --port 80